# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tG4iFcSjH6NVkruYT2vzTpFkP-t54wv9
"""

num = int(input("Enter the number: "))
print("Multiplication Table of", num)
for i in range(1, 11):
   print(num,"X",i,"=",num * i)