# -*- coding: utf-8 -*-
"""Copy of Untitled57.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bw43ZpLYWVYu-kv0l9dGL9EL65A7crzS
"""

def reverse(string): 
 
    string = string[::-1] 
 
    return string 
a = "Anil Kumar"
print ("The original string  is : ",end="") 
print (a) 
 
print ("The reversed string is : ",end="") 
 
print (reverse(a))