# -*- coding: utf-8 -*-
"""Copy of Untitled51.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8jU9S_LHFJmrxLo6ZEGXR6nPPJodAQN
"""

binary = input("Enter the number in Binary Format: ");
if binary == 'x':
    exit();
else:
    decimal = int(binary, 2);
    print(binary,"in Decimal =",decimal);