# -*- coding: utf-8 -*-
"""Copy of Untitled52.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sTu9WXw22Yixu_g8MimLSV6IQc5WR6Cc
"""

def Fibonacci(n): 
 
    if n<0: 
 
        print("Incorrect input") 
 
    elif n==1: 
 
        return 0
 
     
    elif n==2: 
 
        return 1
 
    else: 
 
        return Fibonacci(n-1)+Fibonacci(n-2) 
 
print(Fibonacci(10))